### ISSUE TITLE
Elasticsearch Linking Support

### ISSUE THREAD

**Issue by pazoozooCH** [marcbachmann/dockerfile-kibana4#5]
You allow to specify the Elasticsearch URL by the environment variable _ELASTICSEARCH_. However, that's not that helpful when trying to connect to a linked Elasticsearch Docker container.

Could you add support to build the URL automatically if the linking environment variables are present? I would suggest using a default link name like _elasticsearch_. In this case, you could check for the presence of the following environment variables:
- ELASTICSEARCH_PORT_9200_TCP_ADDR: IP Address of the Elasticsearch Conainer
- ELASTICSEARCH_PORT_9200_TCP_PORT: Port of the Elasticsearch service

If these variables are present, you could build the URL like this: _http://$ELASTICSEARCH_PORT_9200_TCP_ADDR:$ELASTICSEARCH_PORT_9200_TCP_PORT_

**Comment by marcbachmann** [comment]
Yes. That's a good idea. But how often does the linked container have the
name 'elasicsearch'? In most cases its named differently.

**Comment by pazoozooCH** [comment]
The name of the linked container does not have to be the same as the name of the actual container. Consider you have a elasticsearch container named _myes_. You can then run the kibana container like this: _docker run ... --link myes:elasticsearch ..._

This will "map" the name myes to the name _elasticsearch_ within the container, i.e. determine the names of the env variables accordingly. In short, a naming convention for the link name doesn't impose any restrictions on the naming of the container.

**Comment by marcbachmann** [comment]
That got implemented.
